/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TutoriasISO;

/**
 *
 * @author Paola
 */
public class Fat32 extends javax.swing.JFrame {

    /**
     * Creates new form Fat32
     */
    public Fat32() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnRegresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        ingles = new javax.swing.JButton();
        español = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Fat 32");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, 30));

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPane1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextPane1.setText("Su objetivo fue superar el límite de tamaño de una partición que tenía el FAT16 y mantener la compatibilidad con MS-DOS.\n\nEl tamaño máximo de un archivo en FAT32 es de 4 gigabytes menos 1 byte.\n\nEsta vez Microsoft decidió utilizar direcciones de clústeres de 32 bits (aunque realmente sólo 28 de esos bits se utilizan). Esto permitiría utilizar 268.435.538 clústeres, significando unos 8 terabytes de almacenamiento con clústeres de 32 KB, pero el sector de boot emplea un campo de 32 bits, limitando el tamaño de volumen al tamaño de 2 terabytes en un disco duro de sectores de 512 bytes.\n\nMás tarde, Windows 2000 y XP limitaron la FAT32 a los 32 GB por, según aclararon, decisiones de diseño. De todas maneras, ambos sistemas pueden leer y escribir en sistemas FAT32 de cualquier tamaño.\n\nTambién el tamaño máximo de un archivo en FAT32 es de 4 gigabytes menos 1 byte.\n\nLas grandes bases de datos, videos y demás, exceden fácilmente este límite, por lo tanto requerirían de otros sistemas de archivos, como ser NTFS.\n\nTomado el 20/Agosto/18 de: [http://www.alegsa.com.ar/Dic/fat32.php]");
        jTextPane1.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 390, 270));

        btnRegresar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\if_InterfaceExpendet-02_592613.png")); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 160, 40));

        btnSalir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\if_free-29_618316.png")); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 150, 40));

        ingles.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\eu.png")); // NOI18N
        ingles.setToolTipText("Ingles");
        ingles.setContentAreaFilled(false);
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        getContentPane().add(ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 30, -1));

        español.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\if_Spain_298518.png")); // NOI18N
        español.setContentAreaFilled(false);
        español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                españolActionPerformed(evt);
            }
        });
        getContentPane().add(español, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 30, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\fat32.png")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 249));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 300, 270));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\up2.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\blanco2.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        //Tambien se puede poner
        //this.setVisible(false);

        FatTypes fat= new FatTypes();
        fat.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        // TODO add your handling code here:
        jTextPane1.setText("Its goal was to exceed the size limit of a partition that had the FAT16 and maintain compatibility with MS-DOS.\n" +
"\n" +
"The maximum size of a file in FAT32 is 4 gigabytes minus 1 byte.\n" +
"\n" +
"This time Microsoft decided to use addresses of 32-bit clusters (although really only 28 of those bits are used). This would allow using 268,435,538 clusters, meaning about 8 terabytes of storage with clusters of 32 KB, but the boot sector uses a 32-bit field, limiting the volume size to the size of 2 terabytes on a hard disk of 512 sectors bytes.\n" +
"\n" +
"Later, Windows 2000 and XP limited the FAT32 to 32 GB by, as clarified, design decisions. In any case, both systems can read and write on FAT32 systems of any size.\n" +
"\n" +
"Also the maximum size of a file in FAT32 is 4 gigabytes minus 1 byte.\n" +
"\n" +
"Large databases, videos and others easily exceed this limit, therefore they would require other file systems, such as NTFS.\n" +
"\n" +
"Taken on 20 / August / 18 from: [http://www.alegsa.com.ar/Dic/fat32.php]");

    }//GEN-LAST:event_inglesActionPerformed

    private void españolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_españolActionPerformed
        // TODO add your handling code here:
        jTextPane1.setText("Su objetivo fue superar el límite de tamaño de una partición que tenía el FAT16 y mantener la compatibilidad con MS-DOS.\n" +
"\n" +
"El tamaño máximo de un archivo en FAT32 es de 4 gigabytes menos 1 byte.\n" +
"\n" +
"Esta vez Microsoft decidió utilizar direcciones de clústeres de 32 bits (aunque realmente sólo 28 de esos bits se utilizan). Esto permitiría utilizar 268.435.538 clústeres, significando unos 8 terabytes de almacenamiento con clústeres de 32 KB, pero el sector de boot emplea un campo de 32 bits, limitando el tamaño de volumen al tamaño de 2 terabytes en un disco duro de sectores de 512 bytes.\n" +
"\n" +
"Más tarde, Windows 2000 y XP limitaron la FAT32 a los 32 GB por, según aclararon, decisiones de diseño. De todas maneras, ambos sistemas pueden leer y escribir en sistemas FAT32 de cualquier tamaño.\n" +
"\n" +
"También el tamaño máximo de un archivo en FAT32 es de 4 gigabytes menos 1 byte.\n" +
"\n" +
"Las grandes bases de datos, videos y demás, exceden fácilmente este límite, por lo tanto requerirían de otros sistemas de archivos, como ser NTFS.\n" +
"\n" +
"Tomado el 20/Agosto/18 de: [http://www.alegsa.com.ar/Dic/fat32.php]");

    }//GEN-LAST:event_españolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fat32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fat32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fat32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fat32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fat32().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton español;
    private javax.swing.JButton ingles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
