/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TutoriasISO;

/**
 *
 * @author Paola
 */
public class Smarttv extends javax.swing.JFrame {

    /**
     * Creates new form Smarttv
     */
    public Smarttv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        ingles = new javax.swing.JButton();
        español = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPane1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextPane1.setText("Es un televisor inteligente. Inteligente por que son televisores en los que a parte de servir para ver la televisión, con ellos podemos navegar por internet y llevan incorporado Blu-Ray con los que podemos reproducir DVD de alta definición. El Blu-Ray se diferencia del DVD en que los discos pueden almacenar mucha más información y conmás calidad.\n\nAdemás también incorporan home cinema para ver la televisión como si estuviéramos en el cine. Podemos grabar y reproducir películas y también podemos navegar por internet y dejar comentarios en nuestro facebook, tuenti, utilizar nuestro correo electrónico, descargar videos de youtube, etc., así como conectar dispositivos externos a través de sus puertos.\n\nY para rematar incluso podemos instalar software en nuestro propio televisor y usarlo como si fuera un ordenador.\n\n\nTomado el 20/Agosto/18 de: [https://es.wikipedia.org/wiki/Sistema_de_archivos]");
        jTextPane1.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 400, 270));

        ingles.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\eu.png")); // NOI18N
        ingles.setToolTipText("Ingles");
        ingles.setContentAreaFilled(false);
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });
        getContentPane().add(ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 30, -1));

        español.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\if_Spain_298518.png")); // NOI18N
        español.setContentAreaFilled(false);
        español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                españolActionPerformed(evt);
            }
        });
        getContentPane().add(español, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 30, -1));

        btnRegresar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\if_InterfaceExpendet-02_592613.png")); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 160, 40));

        btnSalir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\if_free-29_618316.png")); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 150, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\37111-min.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Smart TV");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 37, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\up2.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paola\\Pictures\\SO\\blanco2.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        // TODO add your handling code here:
        jTextPane1.setText("It's a smart TV. Intelligent because they are televisions in which apart from serving to watch television, with them we can surf the internet and have built-in Blu-Ray with which we can play high definition DVDs. Blu-Ray differs from DVD in that discs can store much more information and more quality.\n" +
"\n" +
"They also incorporate home cinema to watch television as if we were in the cinema. We can record and play movies and we can also surf the internet and leave comments on our facebook, tuenti, use our email, download videos from youtube, etc., as well as connect external devices through their ports.\n" +
"\n" +
"And to top it off we can even install software on our own television and use it as if it were a computer.\n" +
"\n" +
"\n" +
"Taken on 20 / August / 18 of: [https://es.wikipedia.org/wiki/Sistema_de_archivos]");
    }//GEN-LAST:event_inglesActionPerformed

    private void españolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_españolActionPerformed
        // TODO add your handling code here:
        jTextPane1.setText("Es un televisor inteligente. Inteligente por que son televisores en los que a parte de servir para ver la televisión, con ellos podemos navegar por internet y llevan incorporado Blu-Ray con los que podemos reproducir DVD de alta definición. El Blu-Ray se diferencia del DVD en que los discos pueden almacenar mucha más información y conmás calidad.\n" +
"\n" +
"Además también incorporan home cinema para ver la televisión como si estuviéramos en el cine. Podemos grabar y reproducir películas y también podemos navegar por internet y dejar comentarios en nuestro facebook, tuenti, utilizar nuestro correo electrónico, descargar videos de youtube, etc., así como conectar dispositivos externos a través de sus puertos.\n" +
"\n" +
"Y para rematar incluso podemos instalar software en nuestro propio televisor y usarlo como si fuera un ordenador.\n" +
"\n" +
"\n" +
"Tomado el 20/Agosto/18 de: [https://es.wikipedia.org/wiki/Sistema_de_archivos]]");
    }//GEN-LAST:event_españolActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        //Tambien se puede poner
        //this.setVisible(false);

        FatTypes fat= new FatTypes();
        fat.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Smarttv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Smarttv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Smarttv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Smarttv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Smarttv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton español;
    private javax.swing.JButton ingles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
